[tool.black]
line-length = 180  # avoid fucking up the code  

[tool.isort]
atomic = true
profile = "black"
line_length = 120
force_single_line = true
known_first_party = ["black"]

[tool.ruff]
line-length = 120
